### ISSUE TITLE
Cannot be installed via manifest.

### ISSUE THREAD

**Issue by apoapostolov** [HadaIonut/EEEG-importer#2]
![image](https://user-images.githubusercontent.com/4083812/102664461-7ee30980-418b-11eb-85f2-9cb9e53620cd.png)

**Comment by ryceg** [comment]
What link are you using to install? Does https://github.com/HadaIonut/EEEG-importer/releases/download/1.0.0/module.json work?

**Comment by sneat** [comment]
Installing via the Add-on Modules section (the built in one) works fine with the 1.0.0 release.
