### ISSUE TITLE
Import does not function for Foundry 0.8.x

### ISSUE THREAD

**Issue by dccrain** [HadaIonut/EEEG-importer#6]
Basically what the title says, this module hasn't been updated for Foundry versions past 0.7.9 and doesn't function.

**Comment by dccrain** [comment]
So using the Import window, paste in the text from the generator. Press the import button, and nothing happens. Here's the console output, folders.forEach is not a function.
Also, the dropdown for the Target folder for npc and actors is not listing any of my folders, just Default and Main Page.
![Screenshot 2021-08-28 005644](https://user-images.githubusercontent.com/11513549/131212451-d8306383-f2dd-4e0a-af77-91d17028b181.png)

**Comment by HadaIonut** [comment]
A few questions: 

- What Foundry version are you using?
- Are you using any modules that do something to folders?
- What version of dnd5e are you using?
- What version of the module are you using? The latest version is 1.1.4. If you are behind update and check again

**Comment by StephenWasntAvailable** [comment]
Hey, not the OP, but was having a similar issue, it was resolved by updating to latest build of EEEG, oddly, the latest build wasn't downloaded when initially installed (I installed it today, it initially installed version 1.0.0, I then updated, and it updated to 1.1.4)

**Comment by HadaIonut** [comment]
Oh, that is my fault 😅 I should update the foundry page for the module more often. Hopefully I will remember to do this in the future.
